// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fggaqvkeqoksljhrwdey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZ2FxdmtlcW9rc2xqaHJ3ZGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjY0NTAsImV4cCI6MjA2ODEwMjQ1MH0.Y7qyBjvRt0KzZGHN7XMr7JNqAl72-JTnP9R3Ednq3HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});